# Generated by Django 4.2.6 on 2023-10-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
    ]
