# Generated by Django 4.2.6 on 2023-10-29 02:15

from django.core.management import call_command
from django.db import migrations


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "book_json.json")


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_book_rating_alter_book_review'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
