# Generated by Django 4.2.6 on 2023-10-25 05:11

from django.db import migrations
from django.core.management import call_command

def load_myinitial_data(apps,schema_editor):
    call_command("loaddata", "book_json.json")

class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20231024_1951'),
    ]

    operations = [
        migrations.RunPython(load_myinitial_data),
    ]
