# Generated by Django 4.2.6 on 2023-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_auto_20231025_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cnt_dipinjam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='is_dipinjam',
            field=models.BooleanField(default=False),
        ),
    ]
