<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-28 08:59
=======
# Generated by Django 4.2.6 on 2023-10-26 06:27
>>>>>>> e4eb0f85e52482f3d749a4d29d3b66c1bc25906e

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('katalog', '__first__'),
=======
>>>>>>> e4eb0f85e52482f3d749a4d29d3b66c1bc25906e
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_dipinjam', models.DateField(null=True)),
                ('durasi_peminjaman', models.IntegerField(null=True)),
                ('tgl_batas', models.DateField(null=True)),
                ('tgl_dikembalikan', models.DateField(null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
