# Generated by Django 4.2.6 on 2023-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tgl_batas',
            field=models.DateField(null=True),
        ),
    ]
