# Generated by Django 4.2.6 on 2023-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_peminjaman_tgl_batas'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='durasi_peminjman',
            field=models.IntegerField(null=True),
        ),
    ]
