# Generated by Django 4.2.6 on 2023-10-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_peminjaman_durasi_peminjman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='durasi_peminjman',
            new_name='durasi_peminjaman',
        ),
    ]
