# Generated by Django 4.2.6 on 2023-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.TextField(max_length=255),
        ),
    ]
