# Generated by Django 4.2.6 on 2023-10-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_adminuser_last_login_alter_adminuser_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tes',
        ),
    ]
