# Generated by Django 4.2.6 on 2023-10-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_auto_20231029_0924'),
        ('review', '0003_product_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='katalog.book'),
        ),
    ]
