# Generated by Django 4.2.6 on 2023-12-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_product_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
