# Generated by Django 5.0 on 2023-12-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20231029_2153'),
        ('laporan_buku_rusak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='katalog.book'),
        ),
    ]
