# Generated by Django 4.2.6 on 2023-10-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_buku_rusak', '0004_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
    ]
