# Generated by Django 4.2.6 on 2023-10-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan_buku_rusak', '0006_product_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
    ]
